# Calico Version master
# https://docs.projectcalico.org/master/releases#master
# This manifest includes the following component versions:
#   calico/ctl:master

apiVersion: v1
kind: ServiceAccount
metadata:
  name: calicoctl
  namespace: kube-system
